import { useMemo, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { useAnimalsQuery } from '../../../hooks/queries/useAnimalsQuery';
import { useNotificationsQuery } from '../../../hooks/queries/useNotificationsQuery';
import { useObjectifsQuery } from '../../../hooks/queries/useObjectifsQuery';
import { useAuthStore } from '../../../stores/useAuthStore';
import { AnimalSelectorItem, AnimalSelectorMore, BottomBar, Chip, EmptyState, ErrorState, FloatingActionButton, GlobalCreateMenu, ObjectiveCard, RootScreen, Skeleton, TopBar, resolveAsyncState, type GlobalCreateTarget } from '../../../shared/components/ui';
import { getAnimalPresence, sortAnimalsForWorkspace } from '../../animals/animalWorkspaceUtils';
import type { Material } from '../../../theme/materials';
import { spacing, typography } from '../../../theme/scales';
import { useAppTheme } from '../../../theme/useAppTheme';
import { formatObjectiveEnd, getInitials, getLinkedAnimals, getObjectiveProgress } from '../../home/homeUtils';
import { tabs, type MainTabId } from '../../home/mainTabs';

type TrackingTab = 'objectives' | 'statistics';
export interface TrackingScreenProps { material?: Material; onSelectTab: (tab: MainTabId) => void; onCreate: (target: GlobalCreateTarget) => void; onCreateObjective: () => void; onOpenObjective: (id: number) => void; onObjectiveActions: (id: number) => void; onStatistics: () => void; onNotifications?: () => void; onAccount?: () => void }

export function TrackingScreen({ material = 'solid', onSelectTab, onCreate, onCreateObjective, onOpenObjective, onObjectiveActions, onStatistics, onNotifications = () => undefined, onAccount = () => undefined }: TrackingScreenProps) {
  const { colors } = useAppTheme(); const user = useAuthStore((state) => state.user); const animalsQuery = useAnimalsQuery(); const objectivesQuery = useObjectifsQuery(); const notificationsQuery = useNotificationsQuery();
  const [selectedAnimalId, setSelectedAnimalId] = useState<number>(); const [activeTab, setActiveTab] = useState<TrackingTab>('objectives'); const [historyExpanded, setHistoryExpanded] = useState(false); const [createOpen, setCreateOpen] = useState(false);
  const animals = sortAnimalsForWorkspace(animalsQuery.data ?? []); const presentAnimals = animals.filter((animal) => getAnimalPresence(animal) === 'present'); const historicalAnimals = animals.filter((animal) => getAnimalPresence(animal) === 'history'); const objectives = objectivesQuery.data ?? [];
  const visible = useMemo(() => selectedAnimalId == null ? objectives : objectives.filter((objective) => objective.animaux.includes(selectedAnimalId)), [objectives, selectedAnimalId]);
  const state = resolveAsyncState({ loading: objectivesQuery.isLoading || animalsQuery.isLoading, error: objectivesQuery.isError || animalsQuery.isError, hasData: objectives.length > 0 });
  const notifications = Array.isArray(notificationsQuery.data) ? notificationsQuery.data : [];
  const selectTrackingTab = (tab: TrackingTab) => { if (tab === 'statistics') onStatistics(); else setActiveTab(tab); };
  const refresh = () => void Promise.all([objectivesQuery.refetch(), animalsQuery.refetch(), notificationsQuery.refetch()]);
  const selectCreate = (target: GlobalCreateTarget) => { setCreateOpen(false); onCreate(target); };
  return <><RootScreen header={<TopBar title="Suivi" material={material} onNotifications={onNotifications} unreadNotifications={notifications.filter((item) => !item.is_read).length} onAccount={onAccount} avatarInitials={getInitials(user?.prenom)} />} bottomBar={<BottomBar items={tabs} activeId="tracking" onSelect={onSelectTab} material={material} testID="main-tabs" />} padded={false} floatingAction={<FloatingActionButton accessibilityLabel="Créer" testID="tracking-create" onPress={() => setCreateOpen(true)} material={material} />} testID="tracking-screen">
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ minWidth: '100%', paddingHorizontal: spacing.sm, paddingTop: spacing.sm, alignItems: 'flex-start' }}><View style={{ flexDirection: 'row' }}>{presentAnimals.map((animal) => <AnimalSelectorItem key={animal.id} name={animal.nom} imageUrl={animal.image} selected={selectedAnimalId === animal.id} selectionRole="radio" onPress={() => setSelectedAnimalId(animal.id)} testID={`tracking-animal-${animal.id}`} />)}{historicalAnimals.length ? <AnimalSelectorMore expanded={historyExpanded} onPress={() => setHistoryExpanded((value) => !value)} testID="tracking-animal-more" /> : null}{historyExpanded ? historicalAnimals.map((animal) => <AnimalSelectorItem key={animal.id} name={animal.nom} imageUrl={animal.image} selected={selectedAnimalId === animal.id} selectionRole="radio" onPress={() => setSelectedAnimalId(animal.id)} testID={`tracking-animal-${animal.id}`} />) : null}</View><View style={{ paddingTop: spacing.lg }}><Chip label="Tous" selected={selectedAnimalId == null} onPress={() => setSelectedAnimalId(undefined)} variant="tonal" /></View></ScrollView>
    <View accessibilityRole="tablist" style={{ height: 48, flexDirection: 'row', paddingHorizontal: spacing.md }}>{([{ id: 'objectives', label: 'Objectifs' }, { id: 'statistics', label: 'Statistiques' }] as const).map((item) => { const active = activeTab === item.id; return <Pressable key={item.id} accessibilityRole="tab" accessibilityState={{ selected: active }} accessibilityLabel={item.id === 'statistics' ? 'Statistiques, Premium' : item.label} onPress={() => selectTrackingTab(item.id)} style={{ flex: 1, alignItems: 'center', justifyContent: 'center', borderBottomWidth: active ? 2 : 1, borderBottomColor: active ? colors.primaryDark : colors.border }}><Text style={{ color: active ? colors.primaryDark : colors.textSecondary, fontFamily: active ? typography.fonts.semiBold : typography.fonts.medium, fontSize: typography.sizes.md }}>{item.label}{item.id === 'statistics' ? ' · Premium' : ''}</Text></Pressable>; })}</View>
    <View style={{ padding: spacing.md, gap: spacing.md }}><View style={{ flexDirection: 'row', alignItems: 'center' }}><Text accessibilityRole="header" style={{ flex: 1, color: colors.textPrimary, fontFamily: typography.fonts.bold, fontSize: typography.sizes.xxl }}>Vos objectifs</Text><Text style={{ color: colors.primaryDark, fontFamily: typography.fonts.semiBold, fontSize: typography.sizes.sm }}>{visible.length} en cours</Text></View>
      {state === 'loading' ? <><Skeleton type="card" density="comfortable" /><Skeleton type="card" density="comfortable" /></> : state === 'error' ? <ErrorState message="Impossible de charger les objectifs." onRetry={refresh} /> : visible.length === 0 ? <EmptyState title={selectedAnimalId == null ? "Aucun objectif pour le moment" : "Aucun objectif pour cet animal"} message="Créez un objectif simple, mesurable et lié à vos animaux." actionLabel="Créer un objectif" onAction={onCreateObjective} /> : visible.map((objective) => { const progress = getObjectiveProgress(objective); const completed = progress >= 1; const overdue = !completed && new Date(objective.datefin).getTime() < Date.now(); return <ObjectiveCard key={objective.id} title={objective.title} status={completed ? 'completed' : overdue ? 'overdue' : 'active'} statusLabel={`${objective.sousetapes.filter((step) => ['done', 'completed', 'termine', 'terminé', 'true'].includes(String(step.state).toLowerCase())).length} / ${objective.sousetapes.length} étapes`} progress={progress} endLabel={formatObjectiveEnd(objective.datefin)} animals={getLinkedAnimals(objective.animaux, animals)} onPress={() => onOpenObjective(objective.id)} onMore={() => onObjectiveActions(objective.id)} testID={`tracking-objective-${objective.id}`} />; })}
    </View>
  </RootScreen><GlobalCreateMenu open={createOpen} onClose={() => setCreateOpen(false)} onSelect={selectCreate} material={material} /></>;
}
