import { Image } from 'expo-image';
import { Text, View } from 'react-native';
import { radii, typography } from '../../../../theme/scales';
import { useAppTheme } from '../../../../theme/useAppTheme';
import { Card } from './Card';
import { DomainBody, DomainCaption, DomainTitle } from './DomainCardParts';

export interface ContactCardProps { name: string; details: string; phoneLabel: string; emergency?: boolean; imageUrl?: string | null; onPress?: () => void; onCall?: () => void; testID?: string }
export function ContactCard({ name, details, phoneLabel, emergency = false, imageUrl, onPress, onCall, testID }: ContactCardProps) { const { colors } = useAppTheme(); const initials = name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]?.toLocaleUpperCase()).join('') || '?'; return <Card onPress={onPress ?? onCall} accessibilityLabel={`${name}, ${details}, ${phoneLabel}`} testID={testID} style={{ width: '100%', maxWidth: 344, height: 112, flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12, borderWidth: emergency ? 2 : 1, borderColor: emergency ? colors.error : colors.border }}><View style={{ width: 56, height: 56, overflow: 'hidden', borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: emergency ? colors.errorSurface : colors.primaryLight }}>{imageUrl ? <Image source={{ uri: imageUrl }} contentFit="cover" style={{ width: '100%', height: '100%' }} /> : <Text style={{ color: emergency ? colors.error : colors.primaryDark, fontFamily: typography.fonts.bold, fontSize: typography.sizes.lg }}>{initials}</Text>}</View><View style={{ flex: 1, gap: 2 }}><DomainTitle>{name}</DomainTitle><DomainBody numberOfLines={1}>{details}</DomainBody><DomainCaption color={emergency ? colors.error : colors.primaryDark}>{phoneLabel}</DomainCaption></View></Card>; }
