import type { ReactNode } from 'react';
import { Pressable, Text, View } from 'react-native';
import { spacing, typography } from '../../../../theme/scales';
import { useAppTheme } from '../../../../theme/useAppTheme';
import { Icon } from '../icons';

export function DomainTitle({ children, numberOfLines = 1 }: { children: ReactNode; numberOfLines?: number }) { const { colors } = useAppTheme(); return <Text numberOfLines={numberOfLines} style={{ color: colors.textPrimary, fontFamily: typography.fonts.semiBold, fontSize: typography.sizes.lg, lineHeight: 24 }}>{children}</Text>; }
export function DomainLabel({ children, numberOfLines = 1 }: { children: ReactNode; numberOfLines?: number }) { const { colors } = useAppTheme(); return <Text numberOfLines={numberOfLines} style={{ color: colors.textPrimary, fontFamily: typography.fonts.semiBold, fontSize: typography.sizes.md, lineHeight: 22, letterSpacing: 0.1 }}>{children}</Text>; }
export function DomainBody({ children, numberOfLines = 2 }: { children: ReactNode; numberOfLines?: number }) { const { colors } = useAppTheme(); return <Text numberOfLines={numberOfLines} style={{ color: colors.textSecondary, fontFamily: typography.fonts.regular, fontSize: typography.sizes.control, lineHeight: 20 }}>{children}</Text>; }
export function DomainCaption({ children, color, numberOfLines = 1 }: { children: ReactNode; color?: string; numberOfLines?: number }) { const { colors } = useAppTheme(); return <Text numberOfLines={numberOfLines} style={{ color: color ?? colors.textSecondary, fontFamily: typography.fonts.medium, fontSize: typography.sizes.xs, lineHeight: 16, letterSpacing: 0.1 }}>{children}</Text>; }
export function CardHeader({ title, aside, onMore }: { title: string; aside?: ReactNode; onMore?: () => void }) { return <View style={{ width: '100%', flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }}><View style={{ flex: 1 }}><DomainTitle>{title}</DomainTitle></View>{aside}{onMore ? <Pressable accessibilityRole="button" accessibilityLabel="Plus d’actions" onPress={onMore} hitSlop={10} style={{ width: 24, height: 24, alignItems: 'center', justifyContent: 'center' }}><Icon name="moreHorizontal" size="md" /></Pressable> : null}</View>; }
