import { Text, View } from 'react-native';
import { DataVisualization, DetailScreen, EmptyState, ErrorState, EventCard, MetricCard, PeriodSelector, Skeleton, StatisticHistoryGroup, TopBar, type EventCardType } from '../../../shared/components/ui';
import { useStatisticsQuery } from '../../../hooks/queries/useStatisticsQuery';
import type { Material } from '../../../theme/materials';
import { spacing, typography } from '../../../theme/scales';
import { useAppTheme } from '../../../theme/useAppTheme';
import { buildStatisticsQuery, formatStatisticDate, formatStatisticNumber, getActivityHeatmapData, getEventChartData, getEventHistory, getExpenseCategoryData, getHistoryTrend, getLatestNumericHistory, getPhysicalChartData, getStatisticEvents, statisticsPeriodOptions } from '../statisticsUtils';
import type { StatisticDetailType, StatisticsPeriod } from '../types';

interface StatisticDetailScreenProps { type: StatisticDetailType; animalIds: readonly number[]; period: StatisticsPeriod; material?: Material; onPeriodChange: (period: StatisticsPeriod) => void; onBack: () => void }
const config = { poids: { title: 'Poids', unit: 'kg', chart: 'Évolution du poids' }, balades: { title: 'Balades', unit: '', chart: 'Fréquence des balades' }, depenses: { title: 'Dépenses', unit: '€', chart: 'Répartition des dépenses' }, entrainements: { title: 'Entraînements', unit: '', chart: 'Fréquence des entraînements' }, concours: { title: 'Concours', unit: '', chart: 'Fréquence des concours' } } as const;

export function StatisticDetailScreen({ type, animalIds, period, material = 'solid', onPeriodChange, onBack }: StatisticDetailScreenProps) {
  const { colors } = useAppTheme(); const labels = config[type]; const parameters = buildStatisticsQuery(period, animalIds);
  const weightQuery = useStatisticsQuery('poids', parameters, type === 'poids'); const walksQuery = useStatisticsQuery('balades', parameters, type === 'balades'); const expensesQuery = useStatisticsQuery('depenses', parameters, type === 'depenses'); const trainingQuery = useStatisticsQuery('entrainements', parameters, type === 'entrainements'); const competitionQuery = useStatisticsQuery('concours', parameters, type === 'concours');
  const query = type === 'poids' ? weightQuery : type === 'balades' ? walksQuery : type === 'depenses' ? expensesQuery : type === 'entrainements' ? trainingQuery : competitionQuery;
  if (query.isLoading) return <DetailScreen header={<TopBar title={labels.title} context="detail" onBack={onBack} material={material} />}><Skeleton type="card" density="comfortable" /></DetailScreen>;
  if (query.isError) return <DetailScreen header={<TopBar title={labels.title} context="detail" onBack={onBack} material={material} />}><ErrorState message={`Impossible de charger ${labels.title.toLowerCase()}.`} onRetry={() => void query.refetch()} /></DetailScreen>;
  const physical = type === 'poids' ? weightQuery.data : undefined; const eventData = type === 'balades' ? walksQuery.data : type === 'depenses' ? expensesQuery.data : type === 'entrainements' ? trainingQuery.data : type === 'concours' ? competitionQuery.data : undefined;
  const history = type === 'poids' ? (physical?.history ?? []).map((entry) => ({ date: entry.date, value: Number(entry.value), detail: undefined })) : getEventHistory(type, eventData);
  const chartData = type === 'poids' ? getPhysicalChartData(physical) : getEventChartData(type, eventData); const latest = type === 'poids' ? getLatestNumericHistory(physical) : history[0]; const trend = type === 'poids' ? getHistoryTrend(physical) : 0; const selectedPoint = chartData.at(-1);
  const eventGroups = Object.entries(Object.groupBy(getStatisticEvents(eventData), (event) => event.dateevent.slice(0, 10))).sort(([left], [right]) => right.localeCompare(left));
  return <DetailScreen header={<TopBar title={labels.title} context="detail" onBack={onBack} material={material} />} contentContainerStyle={{ paddingBottom: spacing.xxl, gap: spacing.lg }} testID={`statistic-detail-${type}`}>
    <PeriodSelector options={statisticsPeriodOptions} value={period} onChange={onPeriodChange} />
    <View style={{ flexDirection: 'row', gap: spacing.md }}><View style={{ flex: 1 }}><MetricCard label="Valeur" value={latest ? formatStatisticNumber(Number(latest.value), labels.unit) : '—'} trend={trend > 0 ? 'up' : trend < 0 ? 'down' : 'stable'} trendLabel={formatStatisticNumber(Math.abs(trend), labels.unit)} density="compact" material={material} /></View><View style={{ flex: 1 }}><MetricCard label="Entrées" value={String(history.length)} trend="stable" trendLabel={history[0] ? formatStatisticDate(history[0].date) : 'Aucune donnée'} density="compact" material={material} /></View></View>
    <DataVisualization title={labels.chart} type={type === 'depenses' ? 'donut' : type === 'poids' ? 'line' : 'heatmap'} state={history.length ? 'ready' : 'empty'} data={type === 'depenses' ? getExpenseCategoryData(eventData) : chartData} heatmapData={type === 'poids' || type === 'depenses' ? [] : getActivityHeatmapData(eventData)} valueFormatter={(value) => formatStatisticNumber(value, labels.unit)} selected={selectedPoint ? { label: selectedPoint.label, value: formatStatisticNumber(selectedPoint.value, labels.unit) } : undefined} accessibilitySummary={`${history.length} entrées pour ${labels.title.toLowerCase()}`} testID={`statistic-chart-${type}`} />
    <View style={{ gap: spacing.sm }}><Text accessibilityRole="header" style={{ color: colors.textPrimary, fontFamily: typography.fonts.bold, fontSize: typography.sizes.xl }}>Historique</Text>{eventGroups.length ? eventGroups.map(([date, events], index) => <StatisticHistoryGroup key={date} label={formatStatisticDate(date)} summary={`${events?.length ?? 0} événement${(events?.length ?? 0) > 1 ? 's' : ''}`} defaultExpanded={index === 0}>{events?.map((event) => <EventCard key={event.id} type={eventCardType(event.eventtype)} date={formatStatisticDate(event.dateevent)} time={event.heuredebutevent} title={event.nom} description={event.commentaire} />)}</StatisticHistoryGroup>) : history.length ? history.map((entry, index) => <View key={`${entry.date}-${index}`} style={{ minHeight: 44, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.border }}><Text style={{ flex: 1, color: colors.textSecondary, fontFamily: typography.fonts.medium, fontSize: typography.sizes.xs }}>{formatStatisticDate(entry.date)}</Text><Text style={{ color: colors.textPrimary, fontFamily: typography.fonts.semiBold, fontSize: typography.sizes.sm }}>{formatStatisticNumber(entry.value, labels.unit)}{entry.detail ? ` · ${entry.detail}` : ''}</Text></View>) : <EmptyState title="Aucune donnée sur cette période" message="Les prochaines entrées apparaîtront ici." />}</View>
  </DetailScreen>;
}

function eventCardType(type: string): EventCardType {
  return ({ balade: 'walk', depense: 'expense', entrainement: 'training', concours: 'competition' } as const)[type as 'balade' | 'depense' | 'entrainement' | 'concours'] ?? 'other';
}
