import { Text, View } from 'react-native';
import Svg, { Circle, Polyline } from 'react-native-svg';
import { componentTokens } from '../../../../theme/componentTokens';
import { radii, spacing, typography } from '../../../../theme/scales';
import { useAppTheme } from '../../../../theme/useAppTheme';
import { Card } from '../content';
import { Skeleton } from '../feedback';
import { ChartTooltip, type ChartTooltipProps } from './ChartTooltip';
import { clampIntensity, getChartSummary, normalizeChartValues, type ChartDatum } from './chartUtils';

export type DataVisualizationType = 'line' | 'bar' | 'donut' | 'heatmap';
export type DataVisualizationState = 'ready' | 'selected' | 'loading' | 'empty' | 'error';
export interface HeatmapDatum { row: string; column: string; value: number }
export interface DataVisualizationProps { title: string; type: DataVisualizationType; state?: DataVisualizationState; data?: readonly ChartDatum[]; heatmapData?: readonly HeatmapDatum[]; selected?: ChartTooltipProps; valueFormatter?: (value: number) => string; accessibilitySummary?: string; testID?: string }

export function DataVisualization({ title, type, state = 'ready', data = [], heatmapData = [], selected, valueFormatter = String, accessibilitySummary, testID }: DataVisualizationProps) {
  const { colors } = useAppTheme();
  const summary = accessibilitySummary ?? getChartSummary(data);
  return <Card accessibilityLabel={`${title}. ${state === 'error' ? 'Impossible de charger les données' : state === 'empty' ? 'Pas encore assez de données' : summary}`} testID={testID} style={{ width: '100%', maxWidth: componentTokens.content.dataVisualization.width, height: componentTokens.content.dataVisualization.height, gap: 10 }}><Text style={{ color: colors.textPrimary, fontFamily: typography.fonts.semiBold, fontSize: typography.sizes.lg, lineHeight: 24 }}>{title}</Text><View accessibilityElementsHidden style={{ width: '100%', flex: 1 }}>{state === 'loading' ? <ChartLoading /> : state === 'empty' || state === 'error' ? <ChartMessage error={state === 'error'} /> : <><View style={{ flex: 1, justifyContent: 'center' }}>{type === 'line' ? <LinePlot data={data} /> : type === 'bar' ? <BarPlot data={data} /> : type === 'donut' ? <DonutPlot data={data} valueFormatter={valueFormatter} /> : <HeatmapPlot data={heatmapData} />}</View>{state === 'selected' && selected ? <ChartTooltip {...selected} /> : null}</>}</View></Card>;
}

function ChartLoading() { return <View style={{ flex: 1, justifyContent: 'center' }}><Skeleton type="list" density="compact" /></View>; }
function ChartMessage({ error }: { error: boolean }) { const { colors } = useAppTheme(); return <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.md }}><View style={{ width: 40, height: 40, borderRadius: radii.full, backgroundColor: error ? colors.errorSurface : colors.surfaceVariant }} /><Text style={{ color: error ? colors.error : colors.textSecondary, fontFamily: typography.fonts.regular, fontSize: typography.sizes.control }}>{error ? 'Impossible de charger les données' : 'Pas encore assez de données'}</Text></View>; }

function LinePlot({ data }: { data: readonly ChartDatum[] }) { const { colors } = useAppTheme(); const normalized = normalizeChartValues(data); const width = 296; const height = 128; const points = normalized.map((item, index) => `${normalized.length === 1 ? width / 2 : index * width / (normalized.length - 1)},${height - item.normalized * 100 - 14}`).join(' '); return <View style={{ alignItems: 'center', gap: 4 }}><Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><Polyline points={points} fill="none" stroke={colors.primary} strokeWidth={2} /></Svg><AxisLabels data={data} /></View>; }
function BarPlot({ data }: { data: readonly ChartDatum[] }) { const { colors } = useAppTheme(); const normalized = normalizeChartValues(data); return <View style={{ flex: 1, flexDirection: 'row', alignItems: 'flex-end', gap: 12, paddingHorizontal: 2 }}>{normalized.map((item, index) => <View key={`${item.label}-${index}`} style={{ flex: 1, alignItems: 'center', gap: 6 }}><View style={{ width: '70%', minHeight: 8, height: 24 + item.normalized * 88, borderRadius: 6, backgroundColor: item.color ?? (index === 3 ? colors.primary : colors.primaryLight) }} /><Text style={{ color: colors.textSecondary, fontFamily: typography.fonts.medium, fontSize: typography.sizes.xs }}>{item.label}</Text></View>)}</View>; }
function DonutPlot({ data, valueFormatter }: { data: readonly ChartDatum[]; valueFormatter: (value: number) => string }) { const { colors } = useAppTheme(); const total = data.reduce((sum, item) => sum + Math.max(0, item.value), 0) || 1; const radius = 48; const circumference = 2 * Math.PI * radius; let offset = 0; return <View style={{ flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.xl }}><Svg width={128} height={128} viewBox="0 0 128 128">{data.map((item, index) => { const length = Math.max(0, item.value) / total * circumference; const circle = <Circle key={`${item.label}-${index}`} cx={64} cy={64} r={radius} fill="none" stroke={item.color ?? [colors.primary, colors.eventBalade, colors.eventAutre][index % 3]} strokeWidth={14} strokeDasharray={`${length} ${circumference - length}`} strokeDashoffset={-offset} rotation={-90} origin="64, 64" />; offset += length; return circle; })}</Svg><View style={{ flex: 1, gap: spacing.sm }}>{data.map((item, index) => <View key={`${item.label}-${index}`} style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm }}><View style={{ width: 8, height: 8, borderRadius: radii.full, backgroundColor: item.color ?? [colors.primary, colors.eventBalade, colors.eventAutre][index % 3] }} /><Text numberOfLines={1} style={{ flex: 1, color: colors.textSecondary, fontFamily: typography.fonts.medium, fontSize: typography.sizes.xs }}>{item.label} · {valueFormatter(item.value)}</Text></View>)}</View></View>; }
function HeatmapPlot({ data }: { data: readonly HeatmapDatum[] }) { const { colors } = useAppTheme(); const rows = [...new Set(data.map((item) => item.row))]; const columns = [...new Set(data.map((item) => item.column))]; return <View style={{ flex: 1, gap: 5 }}>{rows.map((row) => <View key={row} style={{ flex: 1, flexDirection: 'row', alignItems: 'center', gap: 4 }}><Text style={{ width: 18, color: colors.textSecondary, fontFamily: typography.fonts.medium, fontSize: typography.sizes.xs }}>{row}</Text>{columns.map((column) => { const value = data.find((item) => item.row === row && item.column === column)?.value ?? 0; return <View key={column} style={{ flex: 1, height: 22, borderRadius: 5, backgroundColor: colors.primary, opacity: 0.15 + clampIntensity(value) * 0.85 }} />; })}</View>)}</View>; }
function AxisLabels({ data }: { data: readonly ChartDatum[] }) { const { colors } = useAppTheme(); const shown = data.length <= 3 ? data : [data[0], data[Math.floor((data.length - 1) / 2)], data[data.length - 1]]; return <View style={{ width: '100%', flexDirection: 'row', justifyContent: 'space-between' }}>{shown.map((item, index) => <Text key={`${item.label}-${index}`} style={{ color: colors.textSecondary, fontFamily: typography.fonts.medium, fontSize: typography.sizes.xs, lineHeight: 16 }}>{item.label}</Text>)}</View>; }
