import { Modal, Pressable, Text, View } from 'react-native';
import { componentTokens } from '../../../../theme/componentTokens';
import { alpha } from '../../../../theme/primitives';
import { radii, spacing, typography } from '../../../../theme/scales';
import { useAppTheme } from '../../../../theme/useAppTheme';
import { Button } from '../actions';
import { TextField } from '../forms';
import { formatTimePart, wrapTimePart } from './timeUtils';

export interface TimePickerProps { open: boolean; hour: number; minute: number; onChange: (value: { hour: number; minute: number }) => void; onConfirm: () => void; onClose: () => void; input?: 'wheel' | 'keyboard'; testID?: string }
export function TimePicker({ open, hour, minute, onChange, onConfirm, onClose, input = 'wheel', testID }: TimePickerProps) {
  const { colors } = useAppTheme();
  return <Modal visible={open} transparent animationType="fade" statusBarTranslucent onRequestClose={onClose}><Pressable onPress={onClose} style={{ flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.lg, backgroundColor: colors.overlay }}><Pressable onPress={(event) => event.stopPropagation()} accessibilityRole="summary" accessibilityLabel="Choisir l’heure" testID={testID} style={{ width: '100%', maxWidth: componentTokens.picker.time.width, gap: 18, padding: 20, borderRadius: radii.modal, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, shadowColor: alpha.black16, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 1, shadowRadius: 8, elevation: 8 }}><Text style={{ color: colors.textPrimary, fontFamily: typography.fonts.semiBold, fontSize: typography.sizes.lg, lineHeight: 24 }}>Choisir l’heure</Text><Text accessibilityLiveRegion="polite" style={{ color: colors.textPrimary, fontFamily: typography.fonts.bold, fontSize: typography.sizes.xxxl, lineHeight: 38, letterSpacing: -0.3, textAlign: 'center' }}>{formatTimePart(hour)} : {formatTimePart(minute)}</Text>{input === 'wheel' ? <><TimePartRow value={hour} max={23} onSelect={(value) => onChange({ hour: value, minute })} /><Text style={{ color: colors.textSecondary, fontFamily: typography.fonts.regular, fontSize: typography.sizes.control, lineHeight: 20, textAlign: 'center' }}>Heures 00 à 23 · minutes 00 à 59</Text><TimePartRow value={minute} max={59} onSelect={(value) => onChange({ hour, minute: value })} /></> : <View style={{ flexDirection: 'row', gap: spacing.sm }}><TextField label="Heures" value={formatTimePart(hour)} keyboardType="number-pad" onChangeText={(value) => onChange({ hour: Math.min(23, Math.max(0, Number(value) || 0)), minute })} containerStyle={{ flex: 1 }} /><TextField label="Minutes" value={formatTimePart(minute)} keyboardType="number-pad" onChangeText={(value) => onChange({ hour, minute: Math.min(59, Math.max(0, Number(value) || 0)) })} containerStyle={{ flex: 1 }} /></View>}<Button label="Confirmer" fullWidth onPress={onConfirm} /></Pressable></Pressable></Modal>;
}
function TimePartRow({ value, max, onSelect }: { value: number; max: number; onSelect: (value: number) => void }) { const { colors } = useAppTheme(); return <View accessibilityRole="adjustable" accessibilityValue={{ min: 0, max, now: value }} accessibilityActions={[{ name: 'decrement' }, { name: 'increment' }]} onAccessibilityAction={({ nativeEvent }) => onSelect(wrapTimePart(value, nativeEvent.actionName === 'increment' ? 1 : -1, max))} style={{ flexDirection: 'row', gap: spacing.sm }}>{[-2, -1, 0, 1, 2].map((delta) => { const option = wrapTimePart(value, delta, max); const selected = delta === 0; return <Pressable key={delta} accessibilityRole="button" accessibilityLabel={formatTimePart(option)} accessibilityState={{ selected }} onPress={() => onSelect(option)} style={{ flex: 1, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: radii.pill, backgroundColor: selected ? colors.primary : colors.surfaceVariant }}><Text style={{ color: selected ? colors.textOnPrimary : colors.textPrimary, fontFamily: typography.fonts.medium, fontSize: typography.sizes.control }}>{formatTimePart(option)}</Text></Pressable>; })}</View>; }
