export const componentTokens = {
  button: {
    height: { small: 44, medium: 48, large: 56 },
    paddingX: { small: 12, medium: 16, large: 24 },
    gap: 4,
    stroke: 1,
  },
  spinner: {
    size: { small: 16, medium: 20, large: 24 },
    stroke: { small: 2, medium: 2.5, large: 3 },
  },
  field: { height: 56, stroke: { default: 1, focus: 2 } },
  textArea: { minHeight: 120 },
  optionCard: { height: 88 },
  stepper: { height: 48, width: 220, touchTarget: 44 },
  slider: { trackHeight: 4, thumbSize: 20, touchAreaHeight: 28 },
  mediaUpload: { height: 140, stroke: 2 },
  navigation: {
    topBarHeight: 64,
    bottomBarHeight: 72,
    bottomBarWidth: 358,
    bottomBarMargin: 16,
    bottomItem: { width: 70, height: 56 },
    tabBarHeight: 48,
    tabIndicator: { width: 48, height: 3 },
    step: { size: 32, connectorHeight: 3, connectorMaxWidth: 76 },
    linearProgressHeight: 4,
  },
  bottomSheet: {
    height: { compact: 260, medium: 420, expanded: 680 },
    handle: { width: 40, height: 5 },
    paddingX: 20,
    paddingTop: 10,
  },
  formSheet: {
    heightRatio: 0.88,
    maxHeight: 760,
    minHeight: 420,
    handleAreaHeight: 24,
    handleWidth: 48,
  },
  dialog: { width: 336, iconSize: 44 },
  mediaViewer: { maxWidth: 720, maxHeight: 720, heightRatio: 0.72, headerHeight: 72 },
  actionMenu: { width: 320, itemHeight: 48 },
  actionSheet: { height: 270, itemHeight: 56 },
  picker: {
    selection: { width: 344, height: 500, optionHeight: 52 },
    calendar: { width: 344 },
    time: { width: 320 },
  },
  feedback: {
    width: 360,
    snackbarHeight: 56,
    bannerHeight: 96,
    stateHeight: 260,
    skeletonHeight: { compact: 96, comfortable: 128 },
  },
  content: {
    cardWidth: 340,
    listItemHeight: 72,
    listLeadingSize: 40,
    linkedAnimalSize: 20,
    linkedAnimalOverlap: 6,
    fileItemHeight: 88,
    filePreviewSize: 52,
    animalSelector: { width: 88, height: 106, ringSize: 72, imageSize: 56 },
    metricCard: { width: 164, height: 132 },
    statisticCard: { summaryHeight: 128, overviewHeight: 106 },
    periodSelector: { width: 300, height: 40, itemHeight: 32 },
    dataVisualization: { width: 344, height: 250, plotHeight: 174 },
  },
  screen: {
    contentMaxWidth: 720,
    contentPaddingX: 16,
    contentPaddingY: 16,
    footerPaddingTop: 12,
  },
  selection: { visualSize: 20 },
  switch: { trackWidth: 44, trackHeight: 24, thumbSize: 20 },
} as const;
