import SignInScreen from './SignIn';
import SignUpScreen from './SignUp';
import VerifyEmailScreen from "./VerifyEmail";
import WelcomeScreen from './Welcome';
import HomeScreen from './Home';
import LoadingScreen from './Loading';
import PetsScreen from './Pets';
import ActionScreen from './Action';
import CalendarScreen from './Calendar';
import StatsScreen from './StatsAndObjectifs';
import SettingsScreen from "./Settings";
import OtherScreen from "./Other";
import NoteScreen from "./Note";
import WishScreen from "./Wish";
import FirstPageAddAnimalScreen from "./FirstPageAddAnimal";
import DiscoverPremiumScreen from "./DiscoverPremium";
import AccountScreen from "./Account";
import ContactScreen from "./Contact";
import GroupListScreen from "./GroupList";
import GroupDetailScreen from './GroupDetail';
//import { ForgotPasswordScreen } from './ForgotPasswordScreen';

module.exports = { SignInScreen, SignUpScreen, VerifyEmailScreen, WelcomeScreen, HomeScreen, LoadingScreen, PetsScreen, ActionScreen, CalendarScreen, StatsScreen, SettingsScreen, NoteScreen, WishScreen, FirstPageAddAnimalScreen, DiscoverPremiumScreen, AccountScreen, ContactScreen, OtherScreen, GroupListScreen, GroupDetailScreen };