import type { ComponentProps } from "react";
import { MaterialCommunityIcons } from "@expo/vector-icons";

type GlyphName = ComponentProps<typeof MaterialCommunityIcons>["name"];

export const iconRegistry = {
  add: "plus",
  remove: "minus",
  close: "close",
  back: "arrow-left",
  previous: "chevron-left",
  next: "chevron-right",
  expand: "chevron-down",
  search: "magnify",
  filter: "tune-variant",
  calendar: "calendar-blank-outline",
  time: "clock-outline",
  home: "home-outline",
  agenda: "calendar-month-outline",
  animals: "paw-outline",
  animalScope: "view-grid-outline",
  tracking: "chart-line",
  more: "view-grid-outline",
  otherMenu: "menu",
  moreHorizontal: "dots-horizontal",
  profile: "account-outline",
  notifications: "bell-outline",
  notificationsUnread: "bell",
  info: "information-outline",
  empty: "inbox-outline",
  warning: "alert-outline",
  success: "check",
  error: "alert-circle-outline",
  upload: "tray-arrow-up",
  visibilityOn: "eye-outline",
  visibilityOff: "eye-off-outline",
  medical: "medical-bag",
  compass: "compass-outline",
  stethoscope: "stethoscope",
  circleCheck: "check-circle-outline",
  trophy: "trophy-outline",
  expense: "currency-eur",
  microphone: "microphone-outline",
  pin: "pin-outline",
  edit: "pencil-outline",
  delete: "trash-can-outline",
  share: "share-variant-outline",
  download: "download-outline",
  retry: "refresh",
  file: "file-outline",
  filePdf: "file-pdf-box",
  image: "image-outline",
  duplicate: "content-copy",
  lock: "lock-outline",
  event: "calendar-outline",
  birthday: "gift-outline",
  gift: "gift-outline",
  note: "note-text-outline",
  objective: "chart-bar",
  goal: "bullseye-arrow",
  chartColumn: "chart-bar",
  contact: "account-outline",
  wish: "currency-eur",
  group: "account-multiple-outline",
  heart: "heart-outline",
  star: "star",
  starOutline: "star-outline",
  phone: "phone-outline",
  message: "message-text-outline",
  email: "email-outline",
} as const satisfies Record<string, GlyphName>;

export type VascoIconName = keyof typeof iconRegistry;
